// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV3xaAtLY7OIasZHhsFMTd36mN0tDoIIg',
    appId: '1:871973118310:web:0152bfd8cff259e653a8a7',
    messagingSenderId: '871973118310',
    projectId: 'finalkidway',
    authDomain: 'finalkidway.firebaseapp.com',
    storageBucket: 'finalkidway.firebasestorage.app',
    measurementId: 'G-L4PNXE8CF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB860CDk5YW_NVxqR_KidubB0K-8Bk0GvE',
    appId: '1:871973118310:android:bf80ff1ffc1baedb53a8a7',
    messagingSenderId: '871973118310',
    projectId: 'finalkidway',
    storageBucket: 'finalkidway.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC568Cevf4t4BD47RQxnCeRQHtXNbZeVZE',
    appId: '1:871973118310:ios:abdc8bacfebaf6f653a8a7',
    messagingSenderId: '871973118310',
    projectId: 'finalkidway',
    storageBucket: 'finalkidway.firebasestorage.app',
    iosBundleId: 'com.example.essaiFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC568Cevf4t4BD47RQxnCeRQHtXNbZeVZE',
    appId: '1:871973118310:ios:abdc8bacfebaf6f653a8a7',
    messagingSenderId: '871973118310',
    projectId: 'finalkidway',
    storageBucket: 'finalkidway.firebasestorage.app',
    iosBundleId: 'com.example.essaiFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV3xaAtLY7OIasZHhsFMTd36mN0tDoIIg',
    appId: '1:871973118310:web:067365a96afb4f2d53a8a7',
    messagingSenderId: '871973118310',
    projectId: 'finalkidway',
    authDomain: 'finalkidway.firebaseapp.com',
    storageBucket: 'finalkidway.firebasestorage.app',
    measurementId: 'G-MGK5PN8ZHZ',
  );
}
